name: "test build"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
env:
  ARTIFACT-LINUX-X86_64-EXTENSION: sqlite-ext-linux-x86_64
  ARTIFACT-MACOS-X86_64-EXTENSION: sqlite-ext-macos-x86_64
  ARTIFACT-WINDOWS-X86_64-EXTENSION: sqlite-ext-windows-x86_64
  ARTIFACT-LINUX-X86_64-WHEELS: sqlite-ext-linux-x86_64-wheels
  ARTIFACT-MACOS-X86_64-WHEELS: sqlite-ext-macos-x86_64-wheels
  ARTIFACT-WINDOWS-X86_64-WHEELS: sqlite-ext-windows-x86_64-wheels
jobs:
  build-linux-x86_64-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - run: sudo apt-get update -y && sudo apt-get install -y cmake
      - run: make loadable static
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT-LINUX-X86_64-EXTENSION }}
          path: dist/debug/*
  build-linux-x86_64-python:
    runs-on: ubuntu-latest
    needs: [build-linux-x86_64-extension]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT-LINUX-X86_64-EXTENSION }}
          path: dist/debug/
      - uses: actions/setup-python@v3
      - run: pip install wheel
      - run: make python
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT-LINUX-X86_64-WHEELS }}
          path: dist/debug/wheels/*.whl
  test-linux-x86_64:
    runs-on: ubuntu-latest
    needs: [build-linux-x86_64-extension, build-linux-x86_64-python]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT-LINUX-X86_64-EXTENSION }}
          path: dist/debug/
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT-LINUX-X86_64-WHEELS }}
          path: dist/debug/
      - run: pip install --find-links dist/debug/ sqlite_rot13
      - run: make test-loadable
      - run: make test-python
  build-macos-x86_64-extension:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - run: brew install llvm
      - name: Cache cmake build
        id: cache-cmake-build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build
      - run: make loadable static
        env:
          CC: /usr/local/opt/llvm/bin/clang
          CXX: /usr/local/opt/llvm/bin/clang++
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT-MACOS-X86_64-EXTENSION }}
          path: dist/debug/*
  build-macos-x86_64-python:
    runs-on: macos-latest
    needs: [build-macos-x86_64-extension]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT-MACOS-X86_64-EXTENSION }}
          path: dist/debug/
      - uses: actions/setup-python@v3
      - run: pip install wheel
      - run: make python
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT-MACOS-X86_64-WHEELS }}
          path: dist/debug/wheels/*.whl
  test-macos-x86_64:
    runs-on: macos-latest
    needs: [build-macos-x86_64-extension, build-macos-x86_64-python]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT-MACOS-X86_64-EXTENSION }}
          path: dist/debug/
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT-MACOS-X86_64-WHEELS }}
          path: dist/debug/wheels
      - run: brew install llvm
      - run: /usr/local/opt/python@3/libexec/bin/pip install --find-links dist/debug/wheels sqlite_rot13
      - run: find dist
      - run: make test-loadable python=/usr/local/opt/python@3/libexec/bin/python
      - run: make test-python python=/usr/local/opt/python@3/libexec/bin/python
  build-windows-x86_64-extension:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: "Setup MSYS2"
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: >-
            make
            unzip
            python3-pip
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
      - run: ./vendor/windows_setup.sh
      - run: make loadable static
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT-WINDOWS-X86_64-EXTENSION }}
          path: dist/debug/*
  build-windows-x86_64-python:
    runs-on: windows-latest
    needs: [build-windows-x86_64-extension]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT-WINDOWS-X86_64-EXTENSION }}
          path: dist/debug/
      - uses: actions/setup-python@v3
      - run: pip install wheel
      - run: make python
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT-WINDOWS-X86_64-WHEELS }}
          path: dist/debug/wheels/*.whl
  test-windows-x86_64:
    runs-on: windows-latest
    needs: [build-windows-x86_64-extension, build-windows-x86_64-python]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT-WINDOWS-X86_64-EXTENSION }}
          path: dist/debug/
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT-WINDOWS-X86_64-WHEELS }}
          path: dist/debug/
      - run: pip install --find-links dist/debug/ sqlite_rot13
      - run: make test-loadable
      - run: make test-python
